### ISSUE TITLE
webapp: channel scan: playlist history not cleared

### ISSUE THREAD

**Issue by angelaschmid** [MythTV/mythtv#1008]
* **MythTV version**:
v35-pre, latest master

* **Component**:
webapp

The following did not result in an issue, but might confuse users.

After scanning for channels, deleting the source and re-adding a new source, the previous processed playlist history is still shown.
The old history is also shown in a new web browser session. Only restarting Mythbackend clears the old history.

When pressing "Start Scan" or when opening another source or creating a new source, the Status and the "Downloading Playlist" history should be cleared. 

![Screenshot 2024-12-30 152739](https://github.com/user-attachments/assets/337ad635-3b3f-4782-98da-29bf5358969e)

**Comment by bennettpeter** [comment]
The log is cleared when you click "Start Scan". Did you see a situation when that did not happen?

The scan status is kept so that if you accidentally close the browser or lose the connection, you can open the app again and see the ongoing status. The system only supports 1 scan at a time, so if you try to go into another tab and scan for another device you still see the first scan continuing. I could prevent that but the user could still not scan another device without canceling or completing the prior scan, and I would want them to see the prior scan reults before starting another scan for anlother device. So this seems the best compromise.

**Comment by angelaschmid** [comment]
Thanks for the explanation.

To clarify, the issue seen was not that there was an ongoing scan running.

What confused me (and for sure might confuse others), is that I created a new source and saw the old history of an **unrelated** scan. The scan started at 100%, ungrew to some 60% and grew to 100% (this happened within some 3 seconds), instead of starting from 0%. Cannot recall what happened with the history. (I can check tomorrow once again and comment).

Here are some enhancements to consider:
- Maybe already implemented: When there is an ongoing scan, inform the user scan running for "source" (for sure the stop scan is visible)
- You might have a history for each source
- Otherwise, when no ongoing scan and a different/new source, clear the progress and history
- Pressing "Start Scan" clears the progress and the history
