### ISSUE TITLE
configure: Initial support for enabling the building of MythTV with LTO

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#224]
Migrated from trac: https://code.mythtv.org/trac/ticket/13653

**Comment by warpme** [comment]
Mark,
FYI
I tested these LTO patches on current master building for: x86_64, aarch64 and armv7 targets. 

- x86_64 & arch64 are working ok (no any issues noted.) 

- armv7 target needs disabling inline-asm for ffmpeg - otherwise ffmpeg build fails at assembler parts (I have the same for mainline ffmpeg).

Generally: enabling LTO gives noticeable improvement: experience at using is more smooth and ui responsiveness is faster. difficult to say how much - but noticeable.

in-line asm issue imho is probably because i'm using quite aggressive compile optimizations regarding cpu caps - probably more aggressive than ffmpeg in-line asm assumptions (just hypothesis).
Anyway - even with disabled in-line asm, armv7 code seems to efficient as expected (rpi3b sw decode of 1080hd gives smooth playback with 60-70% cpu load)

For reference - here is mythtv config patch ( https://github.com/warpme/minimyth2/blob/master/script/myth-master/mythtv/files/0197-issue224-EnableLTO-update-config-to-pass-enable-lto-to-ffmpeg-and-expor.patch ) to deal with ffmpeg in-line asm disablement. 
I designed this as configure switch (not auto setting depending on target arch) as i'm assuming in-line asm issue is rather my use-case result (compile optimizations) - not ffmpeg attribute (like bug or implementation attribute).

**Comment by garybuhrmaster** [comment]
> * armv7 target needs disabling inline-asm for ffmpeg - otherwise ffmpeg build fails at assembler parts (I have the same for mainline ffmpeg).

Since this is (apparently, based on your statements) an upstream bug, can you provide a reference to your open FFmpeg bug?  When it is patched upstream the fix (may be able to be) cherry-picked into MythTV.

**Comment by warpme** [comment]
Gary,
Issue holding me with bothering ffmpeg guys with bug report is not enough data points.
Generally I think my armv7 inline-asm issue can be result of following possible:

1. ffmpeg bug (inline-asm are failing for mine gcc declared cpu caps.)
2. lack of ffmpeg inline-asm support for  mine gcc declared cpu caps.)
3. mine toolchain issue is exposing in this corner case. 

I suspect 3 has low probability as i have full canadian-cross compiled distro with distro wide LTO ennoblement (all 620 packages compiled with LTO (except glibc) with no issues - except ffmpeg inline-asm)

To move forward I need prove is ffmpeg compiling ok for arm target with:
`-mthumb -march=armv7-a+simd -mfloat-abi=softfp -O3 -flto -fPIC`

**Comment by mark-kendall** [comment]
Notes from Gary's original ticket for future reference:

>  For individual LTO testing purposes, and depending on whether your disto has changed the default ar/ranlib/nm commands to be the gcc enabled variants, you make need explicitly specify those in your configure, as in:
> 
>    make distclean
>    ./configure --cc=gcc --cxx=g++ --enable-lto --ar=gcc-ar --ranlib=gcc-ranlib --nm="gcc-nm -g"
>    make
> 
> or for the equivalent for clang of the form (alternative is to use gold rather than lld, but the gold linker seems to be mostly dead upstream, so we use the llvm linker):
> 
>    make distclean
>    ./configure --cc=clang --cxx=clang --enable-lto --ar=llvm-ar --ranlib=llvm-ranlib --nm="llvm-nm -g" --extra-ldflags="-fuse-ld=lld"
>    make
> 
> Note: lld creates 8 byte build-ids by default, and some post processing/debugging utilities were/are known to have challenges with those build-ids, so you may need to include -Wl,--build-id=sha1 in the extra-ldflags.
> 
> Note:  If you are using --extra-cflags, you may need to add --extra-ldflags (with equivalent flags) to avoid certain flag merging artifacts during the link stage compilation as the linker will use the flags in the first object files, which might not be ideal for your use case.
> 
>

**Comment by mark-kendall** [comment]
So all patches are in.

I did notice a small odditiy when compiling with lto: there was a linking failure in libmythmpeg2 - but it only happens when using multiple make threads (i.e. make worked - make -j4 did not).

@warpme @garybuhrmaster I'm minded to close this and let the changes sink in. If the ffmpeg issues are a real world problem then we can revisit. OK?

**Comment by garybuhrmaster** [comment]
> So all patches are in.

Thanks!

Although it looks like the CentOS 7 build is failing.  I believe I had tested on CentOS 7, so perhaps that builder has not updated to its latest package versions?

> I did notice a small odditiy when compiling with lto: there was a linking failure in libmythmpeg2 - but it only happens when using multiple make threads (i.e. make worked - make -j4 did not).

Oddity indeed.  FWIW, I have been commonly building with -j4 (and also -j1 for some other testing) and have not seen such failures.  I will keep a watch to see if I can reproduce it.

> @warpme @garybuhrmaster I'm minded to close this and let the changes sink in. If the ffmpeg issues are a real world problem then we can revisit. OK?

I concur.

I do not understand if the code generation issue that requires the additional override is in FFmpeg or a GCC issue, but it is my personal preference that the inlining override should be a different issue if one wants to keep it around (I am of the "only one report per issue" mentality (different bug reports mean different issue, etc.)).

**Comment by garybuhrmaster** [comment]
> Although it looks like the CentOS 7 build is failing. I believe I had tested on CentOS 7, so perhaps that builder has not updated to its latest package versions?

FWIW I just compiled MythTV under a mock CentOS 7 and got the same errors (I really thought I had tested there).  While CentOS 7 is technically (according to the project's support pages) no longer a supported distro (latest EL would mean EL 8), I'll see if I can provide a solution for EL7 for the master branch if the project desires.

**Comment by mark-kendall** [comment]
I'm slightly baffled by the build failure - V4L2_CTRL_TYPE_U8 has been around for 6 years. Surely CentOS 7 doesn't have a version of v4l2 headers that old?

**Comment by garybuhrmaster** [comment]
> I'm slightly baffled by the build failure - V4L2_CTRL_TYPE_U8 has been around for 6 years. Surely CentOS 7 doesn't have a version of v4l2 headers that old?

Unfortunately, EL7 does appear to have really old headers with the default RH derived kernel headers (3.10.something).  It is apparently one more reason that EL7 is difficult to compile master for (one also needs to be running the software collections (non-RH default) compiler).  If one is using a recent ML LTS kernel headers (from the CentOS 7 ML LTS kernel repo) things compile fine.  Arguable MythTV could require one to use ML LTS kernel headers for building (for CentOS 7 that would be a `yum-config-manager --enable centos-kernel` and `yum upgrade` for both the headers and the kernel, or just upgrade the headers as a one time thing using something like `yum --enable-repo centos-kernel upgrade kernel-headers`).  Checking my test VM, I have been running with ML LTS kernels (and the software collection compilers).  This (installing newer kernel headers) could probably be added to ansible if desired.

**Comment by mark-kendall** [comment]
@garybuhrmaster I haven't checked but I am assuming the v4l2 header removal is a direct requirement for lto?

**Comment by garybuhrmaster** [comment]
> @garybuhrmaster I haven't checked but I am assuming the v4l2 header removal is a direct requirement for lto?

I have thrown away my notes, but my recollection is yes (otherwise I would not have cared about the library for LTO, but would probably have submitted it is a different cleanup), because the requirements for LTO is that a header must be exactly the same for all uses, and that means you either have to maintain a (local to MythTV) header which works for all the OS's (or manage a number of unique configured versions for the variants) or use the system library version, which is typically a much easier approach moving forward.

Since MythTV already requires a non-standard compiler (which is pending being applied to the ansible repo in trac ticket 13631) to compile master on EL7, I suspect adding `yum --enable-repo centos-kernel upgrade kernel-headers` to the ansible config is the most straightforward path forward to try to continue building there.
