### ISSUE TITLE
ttvdb.py throws exeception error

### ISSUE THREAD

**Issue by mtraxiot** [MythTV/mythtv#298]
* **Platform**: Ubuntu

* **MythTV version**: v31

* **Package version**:[v31.0+fixes.202012292035.0bc3cdfbf7~ubuntu20.04.1

* **Component**: metalookup

### What steps will reproduce the bug?
/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a AU -C 74860

Traceback (most recent call last):
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2710, in <module>
    sys.exit(main())
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2505, in main
    convert_series_to_xml(t, series_season_ep, None)
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2071, in convert_series_to_xml
    if 'poster' not in t.shows[show_id].data['_banners'].keys():
KeyError: '_banners'

### What is the expected behaviour?
meta data lookup retrieved

### Additional information

this command works normally
/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a AU -D 75821
so I assume its data related

**Comment by rcrdnalor** [comment]
Since the commit (8d6eaf2), the script ttvdb.py fails if there is no banner available.
See
https://github.com/MythTV/mythtv/commit/8d6eaf2

However, the returned urls of the above mentioned command prior to this commit
are invalid:

ttvdb.py -l en -a AU -C 74860

<images>
  <image type="coverart" url="http://thetvdb.com/banners/" thumb="http://thetvdb.com/banners/_cache/"/>
  <image type="fanart" url="http://thetvdb.com/banners/" thumb="http://thetvdb.com/banners/_cache/"/>
</images>

This issue is actually twofold:
 - Traceback if there are no banners available
 - Incorrect urls returned for coverart and fanart

**Comment by rcrdnalor** [comment]
The invalid urls returned:
`
<images>
  <image type="coverart" url="http://thetvdb.com/banners/" thumb="http://thetvdb.com/banners/_cache/"/>
  <image type="fanart" url="http://thetvdb.com/banners/" thumb="http://thetvdb.com/banners/_cache/"/>
</images>
`

**Comment by mtraxiot** [comment]
another related issue:

**/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a AU -D 72560 1 1**

Traceback (most recent call last):
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2714, in <module>
    sys.exit(main())
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2584, in main
    displaySeriesXML(t, series_season_ep)
  File "/usr/share/mythtv/metadata/Television/ttvdb.py", line 2167, in displaySeriesXML
    items.find("item").find("images").append(glob_coverart)
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by rcrdnalor** [comment]
@mtraxiot
Do these  changes from Jan 8, 2021 changes work for you?

**Comment by mtraxiot** [comment]
Yes thanks no more exceptions reported
Thanks again for the quick response
