### ISSUE TITLE
thetvdb.com API is changing at end of March and requiring a paid subscription

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#301]
We need to switch to another service for TV metadata.

**Comment by bennettpeter** [comment]
@rcrdnalor is already working on adding tvrage as a grabber.

themoviedb supports TV shows as well as movies. The current moviedb grabber tmdb3.py is coded to only search for movies and returns an error when attempting to use it for TV lookup. 

The current MythTV paradigm requires a separate grabber for movies and TV. I will create a new grabber for TV that uses themoviedb as its source. It will likely call the existing grabber tmdb3.py with an additional parameter to allow TV lookup, while still appearing to MythTV as if it is a separate grabber.

**Comment by rcrdnalor** [comment]
@bennettpeter : I am working on a grabber from tvmaze (https://www.tvmaze.com/)

See pull request #303.
Attributes of this tvmaze TV grabber:
pros:
- free of charge
- compatible to mythtv/fixes/v29+

cons:
- only English, no localization
- less data

**Comment by bennettpeter** [comment]
See pull request #304 .

**Comment by bennettpeter** [comment]
Added tmdb3 as TV grabber ins commit f53465de76

**Comment by rcrdnalor** [comment]
Peter,
Many thanks to the tmdb3tv grabber. It is a great successor to the 
ttvdb grabber script (from thetvdb.com).
Even trakt (https://trakt.tv/) switches to themoviedb.org, see
https://blog.trakt.tv/tmdb-transition-ef3d19a5cf24
There is a link to a comparison chart between those two grabbers,
which is worth to look at.

I suggest to add your name in the file lookup.py as author:
The `__author__` variable does not reflect this.


An interesting topic at
http://lists.mythtv.org/pipermail/mythtv-users/2021-February/406488.html
popped up the question about the compatibility to python2, which is used
in MythTV v30 and below:
There is a trace-back reported for python2 in the file lookup.py,line 300 at:
    if query.isnumeric(): 
which is not compatible to python2.

Even MythTV master does not support python2 anymore, see 
https://www.mythtv.org/wiki/Release_Notes_-_31
I kindly ask you to look at this issue.

Python's `isnumeric` method supports only unicode, but covers all numeral
expressions of different languages, like `一二三`, i.e. `123` in Japanese Kanji.
Since the default type for a string is 'ascii' in python2, this does not work
without type conversion.

Solution: Try 'ascii' string conversion via `isdigit`, if the method
`isnumeric` does not work. This works in python2 and python3 and is 
proofed to work in future.


I have tested the attached patch with 
python2 on MythTV v.29 (python 2.7.17)
python3 on mythTV v.31 (python3.6 and python 3.9)

with the follwing commands:
(substitude X accordingly)

$ pythonX ./tmdb3tv.py -l en -a US -M Monk
$ pythonX ./tmdb3tv.py -l en -a US -N 1695 "Mr. Monk and the Psychic"
$ pythonX ./tmdb3tv.py -l en -a US -N Monk "Mr. Monk and the Psychic"

$ pythonX ./tmdb3tv.py -l de -a AT -M BÖsterreich
$ pythonX ./tmdb3tv.py -l de -a AT -N BÖsterreich "Katholiken und Geiseln"
$ pythonX ./tmdb3tv.py -l de -a AT -D 65205 1 4







Attached patch:

[python2_tmdbtv_numeric_query.zip](https://github.com/MythTV/mythtv/files/6055246/python2_tmdbtv_numeric_query.zip)

**Comment by bennettpeter** [comment]
Thank you fo the fix. I committed it as 00b1eea0ee

**Comment by rcrdnalor** [comment]
See  #377 for a proposal of the implementation of the TheTVDB.com API 4.x :
Add optional metadata grabber for television: ttvdbv4
