### ISSUE TITLE
Signal monitor OSD freezes Live TV

### ISSUE THREAD

**Issue by kmdewaal** [MythTV/mythtv#310]
* **Platform**: Fedora 33

* **MythTV version**: master

* **Package version**: build from source

* **Component**: TV playback

### What steps will reproduce the bug?

When Live TV is started an OSD is shown with the signal strength and the lock status. When the TV playing starts the OSD slowly fades away. This is all correct.

When Live TV is playing this OSD can be shown again by pressing Alt+F7.
This is the default key binding for the action SIGNALMON of context TV Playback.

Pressing Alt+F7 does show the OSD but then Live TV freezes. Also the OSD is frozen.
Pressing backspace removes the OSD but the OSD then comes back immediately.
Pressing Escape removes the OSD and also exits Live TV.

### How often does it reproduce? Is there a required condition?
100% reproducible

### What is the expected behaviour?
Pressing Alt+F7 does show the OSD on top of Live TV and Live TV continues to play.
The OSD updates the signal strength continuously.
Pressing backspace exits the OSD but Live TV continues to play.

###  What do you see instead?

Screenshot of mythfrontend with frozen Live TV with frozen OSD.

![20210130-osd-frozen-livetv](https://user-images.githubusercontent.com/10491032/106368779-91d12800-634c-11eb-92c6-bce203154eeb.png)

**Comment by kmdewaal** [comment]
As reported by David Hampton on the users list, and I can confirm this, the OSD is not frozen as the signal strength is continuously updated Only the video is frozen. I also agree with David that this is likely not a std::chrono issue like issue #312. Maybe the problem is similar to the now-fixed playback OSD issue #271.

**Comment by mark-kendall** [comment]
@kmdewaal @linuxdude42 I've spent a few hours looking at this. I have no idea when or how it was broken but to my eyes it looks like there is more than 1 issue. The key area is the 3 lines starting at:-

https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythtv/tv_play.cpp#L3900

Firstly - in an ideal world we shouldn't have to pause and unpause playback - which triggers a whole host of stuff that really is unnecessary. Playback does however fail if we don't pause before asking the remote encoder to enable signal monitoring; the backend never replies - which I assume is because it requires the recorder to be paused before changing the card's state (I didn't dig very far on that and I don't know the code).

Secondly - when we pause livetv, a 'dummy' entry is inserted at the front of the live tv chain and when we unpause we then try and switch to the last entry in the tv chain - which is not the correct one; this triggers an incorrect/bogus/unnecessary jump in the playback code to the dummy entry - which clears the video buffers amongst other things. If I comment out:-

https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythtv/tv_play.cpp#L9688

then that is fixed - but will presumably break channel changing in various ways. This appears to either be a direct regression or has been around for some time and changes in the playback code have highlighted it.

Thirdly - as previously noted, the signal monitor OSD screen doesn't go away which is probably similar to the previous OSD debug issue

**Comment by kmdewaal** [comment]
When Live TV is paused, by pressing the "P", the playback is halted while the recording continues. After pressing "P" again playback continues from the position where it was halted.
When the signal monitor OSD is requested with the Alt+F7 then both recording and playback are stopped; the last image stays on the screen, giving the impression of paused playback.
Then in the backend the signal monitor is started and the signal values are shown on the OSD. The signal values are continuously updated with a static backdrop.
When the Alt+F7 is pressed again within 10 seconds or so the signal monitor is stopped and Live TV is started again, complete with a new OSD that after a few seconds fades away once TV playback has started.
When the Alt+F7 is pressed again after a much longer time, e.g. one minute or more, then starting TV  playback again fails, as observed with a HDHomeRun cable tuner.

The way the backend works is that when a recording is requested, the signal monitor is started and once there is a valid signal the signal monitor is stopped and the recording is started.
For the signal monitor OSD apparently the signal monitor is started in a way so that always keeps running and the recording is never started.

It is possible that the behavior has always been like this and that my expectation, to see the signal monitor OSD on top while the Live TV keeps on playing, is more of a feature request than a bug report.

**Comment by kmdewaal** [comment]
As the code is working as intended I am now closing this ticket.
