### ISSUE TITLE
Window management quirk in Mythfrontend

### ISSUE THREAD

**Issue by Jpilk** [MythTV/mythtv#333]
* **Platform**:  Fedora 32 5.10.20-100 x86_64,
*  and SL7.9 5.4.105-1.el7.elrepo.x86_64 #1 SMP Thu Mar 11 08:28:06 EST 2021 x86_64 x86_64 x86_64 GNU/Linux. 
* Both using KDE Plasma

* **MythTV version**: MythTV Version : v32-Pre-6911843ed88 built 10 March
MythTV Branch : HEAD -> master

* **Package version**:  Gary B script in Fedora 32

* **Component**: mythfrontend

### What steps will reproduce the bug?

Display a web page like the 'issues' one in Firefox.  Mouse over the $name in an 'Opened by $name' line, which will create two popups; one with an ident, and one linking other issues opened by the same $name. 

If a mythfrontend window is displayed in front of the web page, it will occult the first popup but not the second.  It seems likely that this is related to a known problem in the operation of the cutlist editor, where some operations can hang with a display frozen for 20 seconds

### What is the expected behaviour?
I would expect the second popup to be treated like the first.

### What do you see instead?  
The second (black) popup overwrites the frontend window

**Comment by kmdewaal** [comment]
Testing with page https://github.com/MythTV/mythtv/issues.
On my laptop, with Fedora 33, Wayland, Gnome and Firefox the behavior is as expected. Both popups are obscured by the mythfrontend window.
However, with the Chrome browser the second (black) popup is shown on top of the mythfrontend window as described.
This does not depend on the mythfrontend window; with any other window, e.g. terminal or Files, the behavior is the same.

What the correct behavior of the black popup window is, to be on top or not to be on top of all other windows, and if this should be fixed in Wayland, Gnome, KDE, Firefox,  Chrome or in the Gihub web page is definitely an interesting topic but outside the scope of MythTV.
Closing this ticket.
