### ISSUE TITLE
Out of bounds read for ts header

### ISSUE THREAD

**Issue by KungFuJesus** [MythTV/mythtv#433]
* **Platform**:  Linux mythtvbox 5.15.1-gentoo #1 SMP PREEMPT Tue Nov 9 22:00:19 EST 2021 x86_64 Intel(R) Core(TM)2 Quad CPU Q9650 @ 3.00GHz GenuineIntel GNU/Linux

* **MythTV version**: fixes/31

* **Package version**:

* **Component**: mythavcodec?  Affects likely both backends and frontends

### What steps will reproduce the bug?

Stock mythtv has this issue.  Whether or not it's causing issues on the regular is unknown.

### How often does it reproduce? Is there a required condition?
A transport stream header with a non-zero adaptation field

### What is the expected behaviour?
Properly parse the adaptation field length from the transport stream header

### What do you see instead?
Parsing an out of bounds byte to a an array of 4 bytes explicitly copied into the TSHeaderArray class.

### Additional information
I've not noticed any explicit buggyness because of this (I doubt the ATSC streams I receive have this info), but it is for sure and without a doubt an out of bounds read that is occurring given the constructors I'm seeing.  Unless the code is doing a reinterpret cast somewhere on a random pointer of bytes (which is possible, but probably not ideal), the static use of std::array<uint8_t, 4> is probably problematic here.  GCC's static analysis easily spots this.  As far as I can tell, the headers should be variable length in these circumstances, and perhaps that data should be copied into an extended, optional std::array of sorts.

Here's the code in question:
https://github.com/MythTV/mythtv/blob/fixes/31/mythtv/libs/libmythtv/mpeg/tspacket.h#L93

**Comment by kmdewaal** [comment]
The code in question copies an adaptation field offset if there is a bit set that there actually is an adaptation field.
The array of 4 bytes is the header of the transport stream packet. Each transport stream packet is 188 bytes. The reason why the header is defined as an array of 4 bytes is that these four bytes do have a fixed layout for each and every transport stream packet; the following bytes do depend on the values of bits in these four bytes and can only be parsed using classic pointer arithmetic.Which is what is happening when the adaptation field offset is copied.
This bit of code has been there since 2003 as you can see from the header and is, as far as I understand the code, correct.
It could very well be that, as you suggest, that by making copies it is possible to code this in such a way that it satisfies the static analysis of GCC and other tooling. However, this might incur considerable overhead given that there are a lot of transport stream packets per second and this can easily introduce new bugs.
I did actually find and fixed a bug in this bit of code a while ago, see commit 2b0cfba827fa889f907f7a8cf0175fe360aae7a0, but I am not aware of other bugs here at this moment. But that does not mean that there are no bugs left....
If you have found a bug then please also add e.g. valgrind output, or a patch that gives additional log output when a critical condition is identified.

However, as I understand the problem report, there is no issue other than the report of the static analysis which is not a reason to rewrite the code. Therefore closing the ticket.

**Comment by KungFuJesus** [comment]
While I follow the variable length header paradigm, the problem is it's reading from memory backed by std::array<> of a fixed width (4).  The only way this doesn't crash or present undefined behavior is if something does an reinterpret_cast of an existing buffer.  I'm not sure that this is happening because there's an explicit constructor.  You'll notice the constructor copies in 4 and _only_ 4 bytes.  How is this correct _unless_ an oversized buffer from the transport stream is pulled and and later parsed here with casting?  Now, if that's happening, surely can be ok, provided that this is never called on explicitly consructed instances of this tsheader class.

**Comment by KungFuJesus** [comment]
Ahh, chasing this down I see that is not a constructor call but rather a reinterpret cast.  I guess what bothers me most is the fact that the constructor exists at all.  It just seems inviting for this class of bug.

**Comment by kmdewaal** [comment]
The code was, as I recall it, originally all C but it has been changed into Modern C++ in places where this did not do any harm. This does not always help for the clarity of the code. I personally do agree that when numbers are defined in standards documents, such as the size of a TS header, it can be more clear to use the numbers or a #define with these numbers.

**Comment by KungFuJesus** [comment]
This might have been more appropriately setup as a struct with classes rather than a fully qualified class.  Though, I imagine the inheritance going on here might not allow it.  For the sake of robustness wouldn't it make sense to explicitly delete constructors just to prevent future incidental malformed TS headers?  Something, anything, that makes it more clear this is a _parse only_ data type to be pulled from existing buffers pulled out of devices would probably be better than what's there now.
