### ISSUE TITLE
System hang displaying guide when there is no guide data

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#567]
MythTV version 32 and master

If there are channels but no guide data (mythfilldatabase has not run for several weeks), selecting listings in Mythweb, or Program Guide in mythfrontend, or guide in webapp, the system hangs.

The database server uses 100% CPU until killed. The screen locks or responds very slowly.

This is most likely to occur on a test system where mythfilldatabase is not run. However there could be cases where it affects end users, if they are not using listings or have a newly installed system.

Since this affects three different guide displays, it is likely a bug in mythbackend.

**Comment by kmdewaal** [comment]
I just did a "delete from program;" to delete all guide information and then start mythbackend and then start mythfrontend and select the program guide and this works OK, it does not hang. This is with a fixes/32 on my development laptop.

**Comment by garybuhrmaster** [comment]
> I just did a "delete from program;" to delete all guide information and then start mythbackend and then start mythfrontend and select the program guide and this works OK, it does not hang. This is with a fixes/32 on my development laptop.

There are actually four tables associated with guide data (program, credits, programgenres, and programrating), and I did a truncate on the entire set (truncate is typically faster than delete), and am also unable to reproduce the looping/hang issue on the latest fixes/32 on my production backend system using mythweb (it was the easiest/fastest place to test since my frontend system is currently physically remote to my location and my test/development system is currently indisposed).

So, I think it might be worthwhile for Peter to do a full database check to make sure his database engine is not (somehow) corrupt.

**Comment by garybuhrmaster** [comment]
Something else occurred to me.  If the BE has not been running for a long time, shortly after it starts up housekeeping may start, and if you have a lot of stale guide data it can take some time for the process to delete it (as I recall, the housekeeping does the equivalent of "delete from various_program_tables where startdate < today", which, depending on how much guide data is in the database, can take a long long time, especially if the development database server is not optimized for such update activity).

**Comment by bennettpeter** [comment]
I can no longer reproduce this, so I am closing it
