### ISSUE TITLE
local .lrc lyric file next to .mp3 file is not found

### ISSUE THREAD

**Issue by twitham1** [MythTV/mythtv#590]
* **Platform**:
`Linux mythtv 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

* **MythTV version**:
fixes/32

* **Package version**:
  Installed: 2:32.0+fixes.202206181511.a26786f5b4~ubuntu20.04.1

* **Component**:
mythbackend (or perhaps mythutil)

### What steps will reproduce the bug?

Put a .lrc file right next to a .mp3 file in the music directory.  Use same path and basename, only the extension is different.

Play that .mp3 file via Music, hit menu -> Lyrics

Hit menu -> Find Lyrics -> File Lyrics to search again

### How often does it reproduce? Is there a required condition?

always in v32, never in v31

### What is the expected behaviour?

expect local .lrc files to be found and displayed like in v31

### What do you see instead?

"No lyrics found for this track"

### Additional information

In an strace of test command "mythutil --findlyrics --songid 7394" I spotted this:

`stat("\"/var/lib/mythtv/music/KJV/19_Psalms008.lrc", 0x7fff81e9c300) = -1 ENOENT (No such file or directory)`

Notice the double quote before the path.  The file exists, by it is rooted at /var, not "/var.  I'm not yet sure where this wrong double quote is introduced.  But I can confirm this is the problem by stripping the quote out in the python:

```root@mythtv:/usr/share/mythtv/metadata/Music/lyrics# diff -u bak/filelyrics.py filelyrics.py
--- bak/filelyrics.py	2022-06-18 10:11:23.000000000 -0500
+++ filelyrics.py	2022-06-21 17:02:10.859068539 -0500
@@ -1,5 +1,5 @@
 #!/usr/bin/python3
-# -*- coding: UTF-8 -*-
+# -*- coding: utf-8 -*-
 # ----------------------
 """
 Scraper for file lyrics
@@ -27,6 +27,7 @@
         utilities.log(debug, "%s: searching lyrics for %s - %s - %s" % (__title__, lyrics.artist, lyrics.album, lyrics.title))
 
         filename = lyrics.filename
+        filename = re.sub('"', '', filename) # hack!!! remove wrong quotes from v32
         filename = os.path.splitext(filename)[0]
 
         # look for a file ending in .lrc with the same filename as the track minus the extension
@@ -91,7 +92,7 @@
     version = etree.XML(u'<grabber></grabber>')
     etree.SubElement(version, "name").text = __title__
     etree.SubElement(version, "author").text = __author__
-    etree.SubElement(version, "command").text = 'alsong.py'
+    etree.SubElement(version, "command").text = 'filelyrics.py'
     etree.SubElement(version, "type").text = 'lyrics'
     etree.SubElement(version, "description").text = __description__
     etree.SubElement(version, "version").text = __version__
```

After the line 30 addition, then lyrics are found.  But it would be better if the wrong quote was removed from the source.

**Comment by kmdewaal** [comment]
Yes, I can reproduce this.

**Comment by rcrdnalor** [comment]
Obviously, the passed filename of filelyrics.py is surrounded with additional double quotes.
Then, the filename gets split by https://github.com/MythTV/mythtv/blob/f86a7ee0dfb22b5a14fc8d8f2e3907f7d1bc8fda/mythtv/programs/scripts/metadata/Music/lyrics/filelyrics.py#L30

Please check if these additional quotes in the filepath are already in the database:
In a terminal, run (using the password from config.xml)

```
mysql -u mythtv -p mythconverg

MariaDB [mythconverg]> select * from storagegroup where groupname = 'Music';

MariaDB [mythconverg]> select * from music_directories;
```
and post the output.

**Comment by kmdewaal** [comment]
The code that starts execution of filelyrics.py has been changed in commit b50234ef0229f1c08d32149fcb7937b15b75a603.
This commit is about changing a deprecated QProcess::start command with a newer start command but it also adds string quotes around all argument values, as shown by the following strace snippets:

With the fixes/31 version of the code, the command to start fileutils.py is:
`[pid 987583] execve("/usr/bin/python3", ["/usr/bin/python3", "/home/klaas/m32-ts/usr/share/mythtv/metadata/Music/lyrics/filelyrics.py", "--artist=Dana Winner", "--album=Unknown Album", "--title=Tranen in mijn hart", "--filename=/home/klaas/ava/music/Dana Winner/dana winner - tranen in mijn hart.mp3"], 0x7ffff15d7f68 /* 65 vars */ <unfinished ...>
`

In fixes/32 the command is changed to:
`[pid 986172] execve("/usr/bin/python3", ["/usr/bin/python3", "/home/klaas/m32-ts/usr/share/mythtv/metadata/Music/lyrics/filelyrics.py", "--artist=\"Dana Winner\"", "--album=\"Unknown Album\"", "--title=\"Tranen in mijn hart\"", "--filename=\"/home/klaas/ava/music/Dana Winner/dana winner - tranen in mijn hart.mp3\""], 0x7fff6a60c858 /* 65 vars */ <unfinished ...>
`

As the commit log does not describe this change and there is no description of any problem that this commit solves other than replacing a deprecated function my understanding is that this change is not intentional.
Therefore I think that the additional quotes can be removed so that the generated command is identical to that of fixes/31, of course while still using the new start command. A fix is forthcoming.

**Comment by kmdewaal** [comment]
About
```
@@ -1,5 +1,5 @@
 #!/usr/bin/python3
-# -*- coding: UTF-8 -*-
+# -*- coding: utf-8 -*-

```
The "coding:" value is consistently written as UTF-8 in uppercase in all the grabber files. As I do not really understand what this is doing I will not change this but leave that to the original author @paul-h if he feels inclined to do this.


About
```
-    etree.SubElement(version, "command").text = 'alsong.py'
+    etree.SubElement(version, "command").text = 'filelyrics.py'

```
This looks to me a good improvement. Most of the grabbers have their own filename as command value but these two have not:
embedlrc.py has as command alsong.py
genius.py has as command minilyrics.py
As I do not really understand what this is doing and it does not seem to influence the correct operation of the grabbers I would like to leave this also to @paul-h

**Comment by twitham1** [comment]
Thank you for the bug fix!  Now a patch to filelyrics.py is NOT needed.  About the coding line:

* per https://stackoverflow.com/questions/14083111/should-i-use-encoding-declaration-in-python-3 the coding line can simply be removed if we no longer support python 2 since python 3 defaults to utf-8 encoding for the source code
* emacs wouldn't let me write the file with uppercase UTF-8 there, but was fine with lowercase utf-8
* most examples I find out there use lowercase coding: utf-8 in python code

About the commad:

* the command is reported by -v option but doesn't appear to be used by anything
* but why report the wrong command name in -v?

Agree that the author can clarify.
