### ISSUE TITLE
Scanning ATSC channels crashes mythtv-setup

### ISSUE THREAD

**Issue by HFonta** [MythTV/mythtv#681]
Hi,
something changed recently using MythTV for many year occasionally scanning channels for updates.
When scanning locks into a channel mythtv-setup segfault using 32/fixes on Ubuntu. New install using v31 does work as expected.

OS Ubuntu 20.04, 22.04 and 22.10 all amd64
Interestingly enough, it does work correctly with Raspberry Pi 4 arm64.

Tuner is HDHomerun HDHomeRun FLEX DUO HDFX-2US  Firmware: 20221031

HDHRSH[1](109149B5): Added 2 devices from 109149B5
HDHRSH[1](109149B5): Connected to device(109149B5-0)
C  Received Segmentation fault: Code 2, PID 671707136, UID 32713, Value 0x00000000

**Comment by kmdewaal** [comment]
I have occasionally seen crashes in mythtv-setup at the end of the scan but they seem to be related to GUI/window stuff.
You might try using another window manager, e.g. X-Windows instead of Wayland.

However, you report that it segfaults when a channel is locked. That is new to me.
Can you please provide debug information as described here:
https://www.mythtv.org/wiki/Debugging#Getting_a_Backtrace

**Comment by HFonta** [comment]
Tried both XWayland Xorg same result. Also clean install on a different computer using Ubuntu 20.04 where the the factory repo is Myth 31 and all working good as soon as I install ppa:mythbuntu/32 and upgrade, same crash on channel lock.

ppa:mythbuntu/32 has dbg of a different version 20220325 and does not install will take some time to figure out.

Forgot to paste this error yesterday: 
022-12-22 07:13:25.036201 I  HDHRSH[1](109149B5): Connected to device(109149B5-0)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thanks,

**Comment by HFonta** [comment]
Since upgrading to 2:32.0+fixes.202212222205.44f88ed468~ubuntu22.10.1 3 days ago, the problem is gone we can close this.
Thx,
