### ISSUE TITLE
MythTV won't tune channels with Encore ENLTV-FM 5.3

### ISSUE THREAD

**Issue by Multiplexer0** [MythTV/mythtv#705]
* **Platform**:
Xubuntu 22.04.1 LTS x86_64 (5.15.0-58-generic)

* **MythTV version**:
v32

* **Package version**:
32.0+fixes.20220325.f69ce764b7-0ubuntu1

* **Component**:
backend & frontend
### What steps will reproduce the bug?
With Encore ENLTV-FM 5.3 card, configure it as "Analog capture card" or "Analog to MPEG-2 encoder card" in the backend, then in video source use either "default" or "us-cable" as frequency table, scan for channels with default config and try to reproduce any channel in the frontend.

### How often does it reproduce? Is there a required condition?
This happens everytime I run mythfrontend and try to tune a channel from this card.

### What is the expected behaviour?
Tune channels correctly in mythfrontend.

### What do you see instead?
Logs when trying to reproduce something with the card as "Analog Capture Card"
[analog-capture-card-default.log](https://github.com/MythTV/mythtv/files/10527926/analog-capture-card-default.log)
[analog-capture-card-uscable.log](https://github.com/MythTV/mythtv/files/10527927/analog-capture-card-uscable.log)

Logs when trying to reproduce something with the card as "Analog to MPEG-2 Encoder Card"
[analog-mpeg2-default.log](https://github.com/MythTV/mythtv/files/10527959/analog-mpeg2-default.log)
[analog-mpeg2-us-cable.log](https://github.com/MythTV/mythtv/files/10527960/analog-mpeg2-us-cable.log)

### Additional information
This happens on a fresh install of Kubuntu 22.04.1 LTS
This issue is a continuation of [this](https://forum.mythtv.org/viewtopic.php?f=36&t=5257) thread in MythTV forum.

**Comment by kmdewaal** [comment]
First thing to figure out is if it this is recording problem or a playback problem.
With the card configured as a "Analog Capture Card" the log shows that the playback tries to play file /home/recordings/11026_20230128025315.nuv

Question: what is the size of this file? If it is a few or several megabytes then there is recording being done and then it can be a playback issue.

The extension "nuv" suggests that this file is coded as NuppelVideo, a codec from the early days of MythTV when computers were slow. What you could do is, in mythtv-setup, change the Video Compression. From the main menu of mythtv-setup, select "3. Recording Profiles", Software Encoders (V4L based), Live TV, Video Compression.
On my system the choice is between "RTjpeg" and "MPEG-4" and you can try MPEG-4.

With the card configured as "Analog to MPEG-2 Encoder Card" a recording file with extension "mpg" is created but the next line says this file has a size of 0 bytes. I am now fairly confident that your card does not do encoding, so the card should be configured as "Analog Capture Card".

In addition to the frontend logs it would also be interesting to have a log of the backend.

Instead of Live TV you can also try to make a recording. It is possible to configure a "Manual Recording" with a start time and a number of minutes to record like how it was done in the VCR days.
If there is a recording made you can try to play this back with VLC or you use commands as "mediainfo" or "ffmpeg -i" to give some details about the file. You can also post a part of the file here.

**Comment by kmdewaal** [comment]
The best way might be to use a version of MythTV that is old enough to fully support analog television. I suggest to use one of the old MythBuntu distributions, which consist of MythTV plus Ubuntu combined. This will likely not run on the latest & greatest processors, you will need something not too new.
This ticket is now closed.
