### ISSUE TITLE
kswapd0 consuming cpu

### ISSUE THREAD

**Issue by shbrueske** [MythTV/mythtv#782]
I just installed Linux Mint 21.1 Cinnamon. Output of uname -a is:

Linux steve-XPS-8930 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I then load Mythtv. Output of mythbackend --version is:

MythTV Version : v32.0+fixes.20220325.f69ce764b7-0ubuntu1
MythTV Branch : fixes/32
Network Protocol : 91
Library API : 32.20200101-1
QT Version : 5.15.2
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_satip using_vbox using_ceton using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libfftw3 using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_v4l2prime using_x11 using_system_libbluray using_system_libudfread using_systemd_notify using_systemd_journal using_drm using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_drm using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

On reboot and at other times mythtv will consume 600% of the cpu running process kswapd0. Killing the process takes care of the problem.

I searched previous issues and found that in the 2020 timeframe a virus was causing the problem. The fix to that virus was to remove the mythtv crontab and delete ~mythtv/.mythtv/.configrc

I looked for something similar on my system and found that there was indeed a crontab for mythtv. As below:

# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (cron.d installed on Wed Jul 26 14:02:16 2023)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
5 6 * * 0 /home/mythtv/.configrc5/a/upd>/dev/null 2>&1
@reboot /home/mythtv/.configrc5/a/upd>/dev/null 2>&1
5 8 * * 0 /home/mythtv/.configrc5/b/sync>/dev/null 2>&1
@reboot /home/mythtv/.configrc5/b/sync>/dev/null 2>&1
0 0 */3 * * /tmp/.X291-unix/.rsync/c/aptitude>/dev/null 2>&1

And there was a similar directory called ~mythtv/.mythtv/.configrc5

I assume that these are a remake of the old virus and that I should remove them.

The bigger concern is how did they get on my system to begin with?

**Comment by shbrueske** [comment]
This is an update of the issue.

The problem was back this morning. The crontab file and .configrc5 directory were back again. After chasing down how that could be, I discovered that there was an ssh login overnight from this IP 178.62.119.233 in the UK. It is a known abuse site according to abuseIPDB. 

They were able to ssh into my system because of an authorized_keys file in a .ssh directory in the mythtv home directory.

The only way I can think of that this got there was that it came along with my installation. I have no idea where the Linux Mint Software Manager downloads it's packages from.

**Comment by rcrdnalor** [comment]
I close this issue by now, because the MythTV project does not provide any binaries nor does care about user management.
When you created this issue, you have been asked for
 - bug report
 - feature request
 - additional help with MythTV
 
This issue definitely belongs to the third class, which means you should ask on the forum or mailing list for help.
A quick search on the forum for 'kswapd0' results in
https://forum.mythtv.org/viewtopic.php?f=36&t=4087
where exactly your scenario is discussed.

Before you open a new post or append to the current post, you should answer yourself the following questions:

 - Is your mythtv installation behind a firewall/router?
 - Does the router still use the default password?
 - Is the the setup of the router available from the wan (internet) side?
 - Who setup the port-forwarding for ssh on the router for your MythTV box?
 - On the PC running MythTV, does the user 'mythtv' have a dedicated password?
 - Are you running any xmltv services that provides EPG?
 - Do you re-use passwords for multiple services/accounts?
 - Do you use strong passwords?
 - Have you setup key-authentication for ssh?
 - Is mythweb available from the wan/internet?
 - Is mythweb exposed to the internet via ssh or a reverse-proxy?
 - Is mythweb password protected?
