### ISSUE TITLE
can't enable settings changes from web GUI

### ISSUE THREAD

**Issue by cybernard** [MythTV/mythtv#863]
Please fill in as much of the template below as you're able to.

Platform: Distro and output of `uname -a` (Linux/UNIX), or version and 32/64-bit (Windows)
MythTV version: the version of MythTV you are running (master, fixes/31, etc)
Package version: if using a packaged version of MythTV, please provide repository/version
Component: if known, please specify the affected component (e.g. frontend/backend)
-->

* **Platform**:
Linux opensuse tumbleweed

* **MythTV version**:
23.1 newest
* **Package version**:

* **Component**:
brand new web gui
### What steps will reproduce the bug?
1. connect to web gui on 6544
2. select enable writing
3. select reboot the backend
It never unlocks.  
I have waiting hours.
dropped the whole DB and started over.
manually killed the backend and re-launch 
rebooted the whole OS
none of this works

I had to go back to mythtv-setup, and even after completing that it still wouldn't enable for some reason.

### How often does it reproduce? Is there a required condition?
100% of the time
### What is the expected behaviour?
I should click enable and then restart and the options in the web gui should no longer be read only.

### What do you see instead?
the web gui was still read only

**Comment by bennettpeter** [comment]
If you want to update a setting:
1. Log on to backend:6544
2. Select settings (cogwheel)
3. Click Enable Updates
4. Make your setting changes.
5. save your changes.
6. Click Restart Backend
7. Backend will be ready for use. Settings are once again not updateable.
There is no point in clicking Enable Updates and then Restart, because Restart disables updates again.

**Comment by cybernard** [comment]
when I said I restarted I meant restart the backend.
I have clicked Enable and the Restart Backend at least 20 times and it didn't work.

**Comment by bennettpeter** [comment]
It is no use just saying "It didn't work" 
Please explain what you did in detail when you followed the steps 1-7 that I outlined above, and what happened, what message you got, which step failed, etc.

**Comment by cybernard** [comment]
I covered the steps in the original ticket.
1. connect to web gui on 6544
2. select **enable writing**
3. Click **Restart Backend**
------------------------
Everything remains read-only

Now before I connected to the web gui, I did a **git clone** and compiled it from source to get the latest features.

**Comment by bennettpeter** [comment]
For the last time, as I explained in my original response:

If you want to update a setting:

1. Log on to backend:6544
2. Select settings (cogwheel)
3. Click Enable Updates
4. Make your setting changes.
5. save your changes.
6. Click Restart Backend
7. Backend will be ready for use. Settings are once again not updateable.

**There is no point in clicking Enable Updates and then Restart, because Restart disables updates again.**
