### ISSUE TITLE
New Titles feature for Leanfront and Myth new web interface

### ISSUE THREAD

**Issue by jmcgee01** [MythTV/mythtv#898]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.
In mythtvfrontend I am used to finding new shows to record by navigating to ManageRecordings|ScheduleRecordings|SearchLists|New Titles.

**Describe the solution you'd like**
Please describe the desired behaviour.
It would be super to have this functionality in either the web interface or leanfront.  

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.
Currently I keep mythfrontend on my desktop to perform this function.

**Comment by bennettpeter** [comment]
I have not used that feature in mythfrontend. When I try it I get a list of thousands of titles. This is just noise to me. How do you filter it? Please explain what options you like, how you use it and what you expect it to return. I can develop it if I understand what is needed, but I am not going into mythfrontend source to figure out what it is doing and copying that code  into the web app or leanfront.

**Comment by jmcgee01** [comment]
Almost every day I look at the Manage Recordings, Search Lists, New Titles. I do not have thousands of results because I am just recording off-air and it only shows new titles.  I sometimes look at the Movies search, where I can choose number of stars and see movies that match that, or maybe by channel and get alphabetical list of titles.  Of those searches probably new titles is the most used. I can always use the deprecated mythweb or mythfrontend on the desktop computer

**Comment by krisbee** [comment]
I only receive OTA recordings, and schedules direct only pulls 18 days of data, so I only get 40-60 listings when I look in here.  I look in here every two weeks so I can see specials that are on that I am not aware of (example, there is a dog show - interested so I am recording).  Since I don't watch much TV and never commercials, this is the only way I can even tell when new stuff is on.  BUT, it is a hassle to have to go to my mythbackend, fire up frontend just to do this search.  It used to work well in mythweb but then started to deteriorate over the years.  The above four stars, below two stars was fun and I did do that every once in a while.

**Comment by krisbee** [comment]
Example, in frontend, here is the search list for SPECIALS
![Screenshot_20240619_091101](https://github.com/MythTV/mythtv/assets/4095415/895c9b20-3174-4ef0-b950-4add804acd18)

**Comment by bennettpeter** [comment]
The existing search in mythfrontend has a bunch of options and a search string. There are also searches for Movies, Categories, Channels, Time, each with a bunch of options.

Looking at the search for new titles, All, I see it tries to find series episodes less than 3 years old where that title has not been recorded on this system before. The logic is convoluted.

If you can explain what you are looking for in "New Titles" I can try to do something sensible. Are you looking for shows you have not recorded before, or shows that were released recently? Are you looking only for series, or movies as well? I can add some filters to the program guide if I know what is needed.

**Comment by krisbee** [comment]
For me, it is new to me shows that are just being broadcast - usually series premieres.  Since TV Movies aren't really a thing anymore, probably just series premieres and shows.  Like, I missed the new show The 1%, which just started airing - and having something that would have let me search for the new shows I would have seen it and maybe gave it a chance.  I like the one in mythfrontend - I just dont like using mythfrontend since I use Leanfront.
