### ISSUE TITLE
:6544 screen doesn't show all post-processing rules

### ISSUE THREAD

**Issue by krisbee** [MythTV/mythtv#921]
* **Platform**: Ubuntu 22.04LTS, 5.15.0-112-generic

* **MythTV version**: 34/fixes

* **Package version**: 34.0+fixes.202405301103.9b54f1a672~ubuntu22.04.1

* **Component**: backend

### What steps will reproduce the bug?
Rule created with metadata + a post-processing rule

### How often does it reproduce? Is there a required condition?
Every time
### What is the expected behaviour?
To Show BOTH rules as active

### What do you see instead?
Only Metadata Rule, not both listed when you look at that showing's add/edit rule.  If you look at the recording rule,  you see what rule is actually showing.  I think what is happening is it shows the default template on add/edit, but you cant see what rules are applied for that one show, even if it shows Record with Override Options.  I think it should show the rules that are currently in force for that show, even if they are different than default so you know what rule is being applied.

### Additional information

![rule not showing](https://github.com/MythTV/mythtv/assets/4095415/fa812d2e-2bc6-4372-bd82-fde798589ea7)
![rule should look like](https://github.com/MythTV/mythtv/assets/4095415/89279ab2-8ddc-421d-a37b-fb56600a5368)

**Comment by bennettpeter** [comment]
I do not see the problem. I went into recording rules, edited a rule with the pencil icon, selected two post processing jobs. They showed with a comma between the names as you have in your screen shot. I saved, left the dialog, went back in and edited the rule again, and still it shows both with the comma between.

**Comment by krisbee** [comment]
Lets say your general default template only has one rule, Metadata.  Now lets say American Idol has the rule for two post processing jobs, one being metadata, one being the second, when you go into the showing it only shows rule for what your general template is, not that actual recording rule.  If you click on what the rule is for the show, it shows the two rules.  But click on the recording, it shows the default template, not the rule that is being applied for that actual show.  So, you don't know what rule is being applied in general is different than the default template.

**Comment by bennettpeter** [comment]
The Upcoming recordings page has a paperclip and a pencil icon on each line. The pencil updates the rec rule, and the paperclip applies an override to the current showing only. 

If you click the pencil you see the correct jobs and correct other details, and you can update the rule. 

If you click the paperclip it is showing the default settings from the template. Any changes you make here only affect the current showing, so if you changed recording group and did not notice that jobs were back to the default, you would have your updated recording group on that episode, but the jobs would not run for that episode.

I will fix this so that all of the correct recording settings are shown when creating an override.

**Comment by bennettpeter** [comment]
Fixed in commit 50d1845dcf. If there are still problems please re-open this or open a new issue.
