### ISSUE TITLE
[SOLVED] Cannot schedule recordings using web interface in MythTV v35-Pre

### ISSUE THREAD

**Issue by ISO8807** [MythTV/mythtv#948]
* **Platform**: Debian 12.7

* **MythTV version**: v35-Pre

* **Package version**:

* **Component**: Web interface

### What steps will reproduce the bug?

Use the web interface (localhost:6544), choose the Program Guide, select a program. 

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

The Save button should be available to schedule a recording.

### What do you see instead?

The Save button is "grayed out" and cannot be clicked.

### Additional information

I have a similar problem with the Mythling app for Android. This recognises that programs have been set to record, but does not give me the option to record other programs.

However, if I use mythfrontend, I can select a program from the guide and record a showing. That works fine, so there is a critical difference between mythfrontend and network access.

This appears to be the same issue as #897 in May. Should this have been fixed in the version I have?

**Comment by bennettpeter** [comment]
When you click a program in the Guide, you see this
![Screenshot_2024-10-13_12-36-22](https://github.com/user-attachments/assets/de05b852-5a48-4f31-9298-42c996146d38)
The save button is disabled because by default "Do Not Record This Program" is selected in the Schedule Type. If you change the Schedule type to another option such as "Record All Showings", Save becomes enabled.
Does this solve the problem? Otherwise please explain in more detail how this happens. What are you selecting in schedule type?

**Comment by ISO8807** [comment]
Many thanks for the prompt and helpful reply.

What I missed was that the Schedule recording" popup is a scrollable window. It appeared to be complete because of the Close/Save buttons at the bottom. I also missed the scrollbar because it is light gray on my system. If I scroll down I can indeed set the Schedule Type to "Record Only This Showing". The program is then recorded :-)

Recording one showing would seem to be the norm, rather than not recording. Is it possible to have "Record Only This Showing" as the default when scheduling a recording? Having Schedule Type early in the popup window would also help as it's easy to overlook in later options.
